apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MCP_SERVER_URL: "http://mcp-server:8000/mcp/"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  FUNCTION_CALLING_MODEL: "katanemo/Arch-Function-3B"
  TRANSCRIPTION_MODEL: "openai/whisper-base"
  # Internal container path, mapped via hostPath in deployment
  HF_HOME: "/root/.cache/huggingface"
