apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-chat
  template:
    metadata:
      labels:
        app: worker-chat
    spec:
      containers:
      - name: worker-chat
        image: oomersheriff12/ytsummarizer:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info", "-Q", "chat_queue", "--pool=solo", "-n", "worker-chat@%h"]
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: hf-cache
          mountPath: /root/.cache/huggingface
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: hf-cache
        hostPath:
          path: /home/oomer/.cache/huggingface
          type: DirectoryOrCreate
