kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  # Mount /dev to allow GPU device access
  - hostPath: /dev
    containerPath: /dev
  extraPortMappings:
  # Expose backend service NodePort
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
